name: pydlosky
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - numba
  - numbalsoda
  - scipy
  - matplotlib
  - joblib
  - ipykernel
  - pip
  - pip:
      - auto-AUTO
